### ISSUE TITLE
again, the if-clause. Why?

### ISSUE THREAD

**Issue by stopopol** [klimeto/emf2iso#5]
https://github.com/klimeto/emf2iso/blob/c97968c1a3d1315fe366a9c5be6c886aa0eb410d/lib/emfjson2isoxml.php#L14

**Comment by klimeto** [comment]
So the script by default returns ISO metadata of the EMF file defined by $emfXMLUrl.

**Comment by stopopol** [comment]
but why is there a hardcoded url to the Zöbelboden ef record?

**Comment by klimeto** [comment]
Because ZB has been used as a sample one.

**Comment by stopopol** [comment]
for the production version sample code should be removed
